spring:
  profiles.active: default
  main.banner-mode: off
  datasource:
    url: jdbc:h2:mem:mydb;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
feign:
  client:
    config:
      default:
        connectTimeout: 3000
        readTimeout: 3000
  autoconfiguration:
    jackson:
      enabled: true
